In [128]:
import math
import numpy as np
import torch
from torch import nn
from torch.nn import functional as F

In [147]:
xs = torch.arange(4*3, dtype=torch.float).reshape(1, 4, 3)
w_q = nn.Linear(3, 3)
w_k = nn.Linear(3, 3)
w_v = nn.Linear(3, 3)
softmax = nn.Softmax(dim=-1)
multihead_attention = nn.MultiheadAttention(embed_dim=3, num_heads=1, batch_first=True, bias=False)

In [161]:
q = w_q(xs)
k = w_k(xs)
v = w_v(xs)
aw1 = softmax(torch.bmm(q / math.sqrt(3), k.transpose(-2, -1)))
a1 = torch.bmm(aw1, v)
a2, aw2 = multihead_attention(q, k, v, average_attn_weights=False)

In [194]:
q = torch.arange(4*3, dtype=torch.float).reshape(1, 4, 3)
k = torch.arange(4*3, dtype=torch.float).reshape(1, 4, 3)
v = torch.zeros(1, 4, 3)
a_w1 = F.softmax(torch.bmm(q, k.transpose(-2, -1)) / math.sqrt(q.size(-1)), dim=-1)
a1 = torch.bmm(a_w1, v)
a2, a_w2 = multihead_attention(q, k, v, attn_mask=torch.zeros(4, 4), average_attn_weights=False)

In [195]:
a1.shape, a2.shape, aw1.shape, aw2.shape

(torch.Size([1, 4, 3]),
 torch.Size([1, 4, 3]),
 torch.Size([1, 4, 4]),
 torch.Size([1, 1, 4, 4]))

In [196]:
a_w1[0], a_w2[0]

(tensor([[    0.0000,     0.0000,     0.0055,     0.9945],
         [    0.0000,     0.0000,     0.0000,     1.0000],
         [    0.0000,     0.0000,     0.0000,     1.0000],
         [    0.0000,     0.0000,     0.0000,     1.0000]]),
 tensor([[[0.3871, 0.2759, 0.1967, 0.1403],
          [0.6416, 0.2377, 0.0881, 0.0326],
          [0.8085, 0.1557, 0.0300, 0.0058],
          [0.9000, 0.0901, 0.0090, 0.0009]]], grad_fn=<SelectBackward0>))

In [167]:
a1[0], a2[0]

(tensor([[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]),
 tensor([[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]], grad_fn=<SelectBackward0>))

In [168]:
torch.arange(4*3, dtype=torch.float).reshape(4, 3)

tensor([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.],
         [ 6.,  7.,  8.],
         [ 9., 10., 11.]]])

In [169]:
torch.arange(4*3, dtybe=torch.float).reshape(1, 4, 3)

tensor([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.],
         [ 6.,  7.,  8.],
         [ 9., 10., 11.]]])

In [193]:
q, k.transpose(-2, -1), torch.bmm(q, k.transpose(-2, -1))

(tensor([[[ 0.,  1.,  2.],
          [ 3.,  4.,  5.],
          [ 6.,  7.,  8.],
          [ 9., 10., 11.]]]),
 tensor([[[ 0.,  3.,  6.,  9.],
          [ 1.,  4.,  7., 10.],
          [ 2.,  5.,  8., 11.]]]),
 tensor([[[  5.,  14.,  23.,  32.],
          [ 14.,  50.,  86., 122.],
          [ 23.,  86., 149., 212.],
          [ 32., 122., 212., 302.]]]))

In [190]:
F.softmax(torch.tensor([5,5,7,5], dtype=torch.float), dim=-1)

tensor([0.0963, 0.0963, 0.7112, 0.0963])

In [64]:
torch.set_printoptions(precision=4, sci_mode=False)

In [84]:
a = (q[0] @ k[0].T) / math.sqrt(3)
softmax(a) @ v[0]

tensor([[-8.0708,  0.1867,  3.7953],
        [-8.4427,  0.2336,  3.9820],
        [-8.5436,  0.2463,  4.0327],
        [-8.5740,  0.2501,  4.0480]], grad_fn=<MmBackward0>)

In [77]:
torch.dot(q[0, 3, :], k[0, 3, :])

tensor(36.0586, grad_fn=<DotBackward0>)